# AI Refinery Career Agents Configuration

orchestrator:
  agent_list:
    - agent_name: "Resume Assessment Agent"
    - agent_name: "Job Search Agent"
    - agent_name: "Interview Prep Agent"
    - agent_name: "General Career Agent"

utility_agents:
  - agent_class: CustomAgent
    agent_name: "Resume Assessment Agent"
    agent_description: "Analyzes resumes and provides feedback on strengths, improvements, and market readiness."
    config:
      assessment_criteria:
        - technical_skills
        - experience_relevance
        - achievements_quantification
        - formatting_quality
        - keyword_optimization
      scoring_weights:
        technical_skills: 0.3
        experience_relevance: 0.25
        achievements_quantification: 0.2
        formatting_quality: 0.15
        keyword_optimization: 0.1
      feedback_categories:
        strengths: "Highlight positive aspects and standout elements"
        improvements: "Specific actionable recommendations"
        market_readiness: "Overall competitiveness assessment"
        next_steps: "Concrete actions to enhance the resume"

  - agent_class: CustomAgent
    agent_name: "Job Search Agent"
    agent_description: "Helps users find relevant jobs online, suggests platforms, keywords, and search strategies."
    config:
      search_platforms:
        - "LinkedIn"
        - "Indeed"
        - "Glassdoor"
        - "AngelList"
        - "Stack Overflow Jobs"
        - "GitHub Jobs"
      search_strategies:
        keyword_optimization: "Use specific job titles and skills"
        location_targeting: "Focus on location provided on the resume or remote options"
        company_research: "Research target companies and their culture"
      job_categories:
        - "Software Engineering"
        - "Data Science"
        - "Product Management"
        - "DevOps/SRE"
        - "Frontend Development"
        - "Backend Development"
        - "Full Stack Development"

  - agent_class: CustomAgent
    agent_name: "Interview Prep Agent"
    agent_description: "Prepares users for interviews with likely questions, answer strategies, and tips."
    config:
      interview_types:
        - "Technical Interviews"
        - "Behavioral Interviews"
        - "System Design"
        - "Cultural Fit"
        - "Panel Interviews"
      question_categories:
        technical:
          - "Coding challenges"
          - "Algorithm and data structures"
          - "System architecture"
          - "Problem-solving approach"
        behavioral:
          - "Leadership examples"
          - "Conflict resolution"
          - "Team collaboration"
          - "Career goals"
      answer_frameworks:
        STAR: "Situation, Task, Action, Result"
        SOAR: "Situation, Obstacle, Action, Result"
        CAR: "Challenge, Action, Result"

  - agent_class: CustomAgent
    agent_name: "General Career Agent"
    agent_description: "Provides general career guidance, advice, and answers using OpenAI GPT-4."
    config:
      response_style: "conversational"
      expertise_areas:
        - "Career transitions"
        - "Skill development"
        - "Industry insights"
        - "Networking strategies"
        - "Professional growth"
      max_response_length: 500


# super_agents:
#   - agent_class: FlowSuperAgent 
#     agent_name: "Career Counselor Flow" 
#     agent_description: | 
#       The Career Counselor Flow helps users navigate their career paths by providing tailored advice and resources.
    
#     config:
#       goal: |
#         Assist users in improving their career prospects through resume assessment, job search strategies, and interview preparation.
      
#       agent_list: 
#         - agent_name: "Job Search Agent"  # Required.
#           next_step: # User design. These are the tasks that depend on this step and will be executed afterward.
#             - "Interview Prep Agent"
            
#         - agent_name: "Interview Prep Agent"  # Required.