# AI Refinery Career Agents Configuration

orchestrator:
  agent_list:
    - agent_name: "Resume Search Agent"
    - agent_name: "Resume Assessment Agent"
    - agent_name: "Job Search Agent"
    - agent_name: "Interview Prep Agent"
    - agent_name: "General Career Agent"

utility_agents:
  - agent_class: CustomAgent
    agent_name: "Resume Search Agent"
    agent_description: "Searches resume content using semantic vector search in AWS OpenSearch with OpenAI embeddings."
    config: {}

  - agent_class: CustomAgent
    agent_name: "Resume Assessment Agent"
    agent_description: "Analyzes resumes and provides feedback on strengths, improvements, and market readiness."
    config: {}

  - agent_class: CustomAgent
    agent_name: "Job Search Agent"
    agent_description: "Helps users find relevant jobs online, suggests platforms, keywords, and search strategies."
    config: {}

  - agent_class: CustomAgent
    agent_name: "Interview Prep Agent"
    agent_description: "Prepares users for interviews with likely questions, answer strategies, and tips."
    config: {}

  - agent_class: CustomAgent
    agent_name: "General Career Agent"
    agent_description: "Provides general career guidance, advice, and answers using OpenAI GPT-4."
    config: {}
